version: "3.8"

services:
  app:
    image: whstw/moscowweatherarchive:latest
    ports:
      - 8080:8080
    working_dir: /MoscowWeatherArchive
    volumes:
      - ./:/moscowweatherarchive

  reactapp:
    image: whstw/weatherinmoscowreact:latest
    ports:
      - 3000:80

  sqldb:
    image: whstw/weather_sqldb:latest
    volumes:
      - sql-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: weather

volumes:
  sql-data: