version: "3.8"

services:
  app:
    image: whstw/moscowweatherarchive:latest
    ports:
      - 8080:8080
    working_dir: /MoscowWeatherArchive
    volumes:
      - ./:/moscowweatherarchive

  reactapp:
    image: whstw/weatherinmoscowreact:latest
    ports:
      - 3000:80

  sqldb:
    image: whstw/weather_sqldb
    volumes:
      - sql-data:/var/lib/postgresql/data
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  sql-data: